import {
    TimeZone,
} from './i18nUtils';


export const TIME_ZONES: readonly TimeZone[] = [
    {
        countryCode: 'UTC',
        coordinates: '+0+0',
        timeZone   : 'UTC',
    },
    {
        countryCode: 'CI',
        coordinates: '+0519-00402',
        timeZone   : 'Africa/Abidjan',
    },
    {
        countryCode: 'GH',
        coordinates: '+0533-00013',
        timeZone   : 'Africa/Accra',
    },
    {
        countryCode: 'ET',
        coordinates: '+0902+03842',
        timeZone   : 'Africa/Addis_Ababa',
    },
    {
        countryCode: 'DZ',
        coordinates: '+3647+00303',
        timeZone   : 'Africa/Algiers',
    },
    {
        countryCode: 'ER',
        coordinates: '+1520+03853',
        timeZone   : 'Africa/Asmara',
    },
    {
        countryCode: 'ML',
        coordinates: '+1239-00800',
        timeZone   : 'Africa/Bamako',
    },
    {
        countryCode: 'CF',
        coordinates: '+0422+01835',
        timeZone   : 'Africa/Bangui',
    },
    {
        countryCode: 'GM',
        coordinates: '+1328-01639',
        timeZone   : 'Africa/Banjul',
    },
    {
        countryCode: 'GW',
        coordinates: '+1151-01535',
        timeZone   : 'Africa/Bissau',
    },
    {
        countryCode: 'MW',
        coordinates: '-1547+03500',
        timeZone   : 'Africa/Blantyre',
    },
    {
        countryCode: 'CG',
        coordinates: '-0416+01517',
        timeZone   : 'Africa/Brazzaville',
    },
    {
        countryCode: 'BI',
        coordinates: '-0323+02922',
        timeZone   : 'Africa/Bujumbura',
    },
    {
        countryCode: 'EG',
        coordinates: '+3003+03115',
        timeZone   : 'Africa/Cairo',
    },
    {
        countryCode: 'MA',
        coordinates: '+3339-00735',
        timeZone   : 'Africa/Casablanca',
    },
    {
        countryCode: 'ES',
        coordinates: '+3553-00519',
        timeZone   : 'Africa/Ceuta',
        comments   : 'Ceuta, Melilla',
    },
    {
        countryCode: 'GN',
        coordinates: '+0931-01343',
        timeZone   : 'Africa/Conakry',
    },
    {
        countryCode: 'SN',
        coordinates: '+1440-01726',
        timeZone   : 'Africa/Dakar',
    },
    {
        countryCode: 'TZ',
        coordinates: '-0648+03917',
        timeZone   : 'Africa/Dar_es_Salaam',
    },
    {
        countryCode: 'DJ',
        coordinates: '+1136+04309',
        timeZone   : 'Africa/Djibouti',
    },
    {
        countryCode: 'CM',
        coordinates: '+0403+00942',
        timeZone   : 'Africa/Douala',
    },
    {
        countryCode: 'EH',
        coordinates: '+2709-01312',
        timeZone   : 'Africa/El_Aaiun',
    },
    {
        countryCode: 'SL',
        coordinates: '+0830-01315',
        timeZone   : 'Africa/Freetown',
    },
    {
        countryCode: 'BW',
        coordinates: '-2439+02555',
        timeZone   : 'Africa/Gaborone',
    },
    {
        countryCode: 'ZW',
        coordinates: '-1750+03103',
        timeZone   : 'Africa/Harare',
    },
    {
        countryCode: 'ZA',
        coordinates: '-2615+02800',
        timeZone   : 'Africa/Johannesburg',
    },
    {
        countryCode: 'SS',
        coordinates: '+0451+03137',
        timeZone   : 'Africa/Juba',
    },
    {
        countryCode: 'UG',
        coordinates: '+0019+03225',
        timeZone   : 'Africa/Kampala',
    },
    {
        countryCode: 'SD',
        coordinates: '+1536+03232',
        timeZone   : 'Africa/Khartoum',
    },
    {
        countryCode: 'RW',
        coordinates: '-0157+03004',
        timeZone   : 'Africa/Kigali',
    },
    {
        countryCode: 'CD',
        coordinates: '-0418+01518',
        timeZone   : 'Africa/Kinshasa',
        comments   : 'Dem. Rep. of Congo (west)',
    },
    {
        countryCode: 'NG',
        coordinates: '+0627+00324',
        timeZone   : 'Africa/Lagos',
    },
    {
        countryCode: 'GA',
        coordinates: '+0023+00927',
        timeZone   : 'Africa/Libreville',
    },
    {
        countryCode: 'TG',
        coordinates: '+0608+00113',
        timeZone   : 'Africa/Lome',
    },
    {
        countryCode: 'AO',
        coordinates: '-0848+01314',
        timeZone   : 'Africa/Luanda',
    },
    {
        countryCode: 'CD',
        coordinates: '-1140+02728',
        timeZone   : 'Africa/Lubumbashi',
        comments   : 'Dem. Rep. of Congo (east)',
    },
    {
        countryCode: 'ZM',
        coordinates: '-1525+02817',
        timeZone   : 'Africa/Lusaka',
    },
    {
        countryCode: 'GQ',
        coordinates: '+0345+00847',
        timeZone   : 'Africa/Malabo',
    },
    {
        countryCode: 'MZ',
        coordinates: '-2558+03235',
        timeZone   : 'Africa/Maputo',
    },
    {
        countryCode: 'LS',
        coordinates: '-2928+02730',
        timeZone   : 'Africa/Maseru',
    },
    {
        countryCode: 'SZ',
        coordinates: '-2618+03106',
        timeZone   : 'Africa/Mbabane',
    },
    {
        countryCode: 'SO',
        coordinates: '+0204+04522',
        timeZone   : 'Africa/Mogadishu',
    },
    {
        countryCode: 'LR',
        coordinates: '+0618-01047',
        timeZone   : 'Africa/Monrovia',
    },
    {
        countryCode: 'KE',
        coordinates: '-0117+03649',
        timeZone   : 'Africa/Nairobi',
    },
    {
        countryCode: 'TD',
        coordinates: '+1207+01503',
        timeZone   : 'Africa/Ndjamena',
    },
    {
        countryCode: 'NE',
        coordinates: '+1331+00207',
        timeZone   : 'Africa/Niamey',
    },
    {
        countryCode: 'MR',
        coordinates: '+1806-01557',
        timeZone   : 'Africa/Nouakchott',
    },
    {
        countryCode: 'BF',
        coordinates: '+1222-00131',
        timeZone   : 'Africa/Ouagadougou',
    },
    {
        countryCode: 'BJ',
        coordinates: '+0629+00237',
        timeZone   : 'Africa/Porto-Novo',
    },
    {
        countryCode: 'ST',
        coordinates: '+0020+00644',
        timeZone   : 'Africa/Sao_Tome',
    },
    {
        countryCode: 'LY',
        coordinates: '+3254+01311',
        timeZone   : 'Africa/Tripoli',
    },
    {
        countryCode: 'TN',
        coordinates: '+3648+01011',
        timeZone   : 'Africa/Tunis',
    },
    {
        countryCode: 'NA',
        coordinates: '-2234+01706',
        timeZone   : 'Africa/Windhoek',
    },
    {
        countryCode: 'US',
        coordinates: '+515248-1763929',
        timeZone   : 'America/Adak',
        comments   : 'Aleutian Islands',
    },
    {
        countryCode: 'US',
        coordinates: '+611305-1495401',
        timeZone   : 'America/Anchorage',
        comments   : 'Alaska (most areas)',
    },
    {
        countryCode: 'AI',
        coordinates: '+1812-06304',
        timeZone   : 'America/Anguilla',
    },
    {
        countryCode: 'AG',
        coordinates: '+1703-06148',
        timeZone   : 'America/Antigua',
    },
    {
        countryCode: 'BR',
        coordinates: '-0712-04812',
        timeZone   : 'America/Araguaina',
        comments   : 'Tocantins',
    },
    {
        countryCode: 'AR',
        coordinates: '-3436-05827',
        timeZone   : 'America/Argentina/Buenos_Aires',
        comments   : 'Buenos Aires (BA, CF)',
    },
    {
        countryCode: 'AR',
        coordinates: '-2828-06547',
        timeZone   : 'America/Argentina/Catamarca',
        comments   : 'Catamarca (CT); Chubut (CH)',
    },
    {
        countryCode: 'AR',
        coordinates: '-3124-06411',
        timeZone   : 'America/Argentina/Cordoba',
        comments   : 'Argentina (most areas: CB, CC, CN, ER, FM, MN, SE, SF)',
    },
    {
        countryCode: 'AR',
        coordinates: '-2411-06518',
        timeZone   : 'America/Argentina/Jujuy',
        comments   : 'Jujuy (JY)',
    },
    {
        countryCode: 'AR',
        coordinates: '-2926-06651',
        timeZone   : 'America/Argentina/La_Rioja',
        comments   : 'La Rioja (LR)',
    },
    {
        countryCode: 'AR',
        coordinates: '-3253-06849',
        timeZone   : 'America/Argentina/Mendoza',
        comments   : 'Mendoza (MZ)',
    },
    {
        countryCode: 'AR',
        coordinates: '-5138-06913',
        timeZone   : 'America/Argentina/Rio_Gallegos',
        comments   : 'Santa Cruz (SC)',
    },
    {
        countryCode: 'AR',
        coordinates: '-2447-06525',
        timeZone   : 'America/Argentina/Salta',
        comments   : 'Salta (SA, LP, NQ, RN)',
    },
    {
        countryCode: 'AR',
        coordinates: '-3132-06831',
        timeZone   : 'America/Argentina/San_Juan',
        comments   : 'San Juan (SJ)',
    },
    {
        countryCode: 'AR',
        coordinates: '-3319-06621',
        timeZone   : 'America/Argentina/San_Luis',
        comments   : 'San Luis (SL)',
    },
    {
        countryCode: 'AR',
        coordinates: '-2649-06513',
        timeZone   : 'America/Argentina/Tucuman',
        comments   : 'Tucuman (TM)',
    },
    {
        countryCode: 'AR',
        coordinates: '-5448-06818',
        timeZone   : 'America/Argentina/Ushuaia',
        comments   : 'Tierra del Fuego (TF)',
    },
    {
        countryCode: 'AW',
        coordinates: '+1230-06958',
        timeZone   : 'America/Aruba',
    },
    {
        countryCode: 'PY',
        coordinates: '-2516-05740',
        timeZone   : 'America/Asuncion',
    },
    {
        countryCode: 'CA',
        coordinates: '+484531-0913718',
        timeZone   : 'America/Atikokan',
        comments   : 'EST - ON (Atikokan); NU (Coral H)',
    },
    {
        countryCode: 'BR',
        coordinates: '-1259-03831',
        timeZone   : 'America/Bahia',
        comments   : 'Bahia',
    },
    {
        countryCode: 'MX',
        coordinates: '+2048-10515',
        timeZone   : 'America/Bahia_Banderas',
        comments   : 'Central Time - Bahia de Banderas',
    },
    {
        countryCode: 'BB',
        coordinates: '+1306-05937',
        timeZone   : 'America/Barbados',
    },
    {
        countryCode: 'BR',
        coordinates: '-0127-04829',
        timeZone   : 'America/Belem',
        comments   : 'Para (east); Amapa',
    },
    {
        countryCode: 'BZ',
        coordinates: '+1730-08812',
        timeZone   : 'America/Belize',
    },
    {
        countryCode: 'CA',
        coordinates: '+5125-05707',
        timeZone   : 'America/Blanc-Sablon',
        comments   : 'AST - QC (Lower North Shore)',
    },
    {
        countryCode: 'BR',
        coordinates: '+0249-06040',
        timeZone   : 'America/Boa_Vista',
        comments   : 'Roraima',
    },
    {
        countryCode: 'CO',
        coordinates: '+0436-07405',
        timeZone   : 'America/Bogota',
    },
    {
        countryCode: 'US',
        coordinates: '+433649-1161209',
        timeZone   : 'America/Boise',
        comments   : 'Mountain - ID (south); OR (east)',
    },
    {
        countryCode: 'CA',
        coordinates: '+690650-1050310',
        timeZone   : 'America/Cambridge_Bay',
        comments   : 'Mountain - NU (west)',
    },
    {
        countryCode: 'BR',
        coordinates: '-2027-05437',
        timeZone   : 'America/Campo_Grande',
        comments   : 'Mato Grosso do Sul',
    },
    {
        countryCode: 'MX',
        coordinates: '+2105-08646',
        timeZone   : 'America/Cancun',
        comments   : 'Eastern Standard Time - Quintana Roo',
    },
    {
        countryCode: 'VE',
        coordinates: '+1030-06656',
        timeZone   : 'America/Caracas',
    },
    {
        countryCode: 'GF',
        coordinates: '+0456-05220',
        timeZone   : 'America/Cayenne',
    },
    {
        countryCode: 'KY',
        coordinates: '+1918-08123',
        timeZone   : 'America/Cayman',
    },
    {
        countryCode: 'US',
        coordinates: '+415100-0873900',
        timeZone   : 'America/Chicago',
        comments   : 'Central (most areas)',
    },
    {
        countryCode: 'MX',
        coordinates: '+2838-10605',
        timeZone   : 'America/Chihuahua',
        comments   : 'Mountain Time - Chihuahua (most areas)',
    },
    {
        countryCode: 'CR',
        coordinates: '+0956-08405',
        timeZone   : 'America/Costa_Rica',
    },
    {
        countryCode: 'CA',
        coordinates: '+4906-11631',
        timeZone   : 'America/Creston',
        comments   : 'MST - BC (Creston)',
    },
    {
        countryCode: 'BR',
        coordinates: '-1535-05605',
        timeZone   : 'America/Cuiaba',
        comments   : 'Mato Grosso',
    },
    {
        countryCode: 'CW',
        coordinates: '+1211-06900',
        timeZone   : 'America/Curacao',
    },
    {
        countryCode: 'GL',
        coordinates: '+7646-01840',
        timeZone   : 'America/Danmarkshavn',
        comments   : 'National Park (east coast)',
    },
    {
        countryCode: 'CA',
        coordinates: '+6404-13925',
        timeZone   : 'America/Dawson',
        comments   : 'MST - Yukon (west)',
    },
    {
        countryCode: 'CA',
        coordinates: '+5946-12014',
        timeZone   : 'America/Dawson_Creek',
        comments   : 'MST - BC (Dawson Cr, Ft St John)',
    },
    {
        countryCode: 'US',
        coordinates: '+394421-1045903',
        timeZone   : 'America/Denver',
        comments   : 'Mountain (most areas)',
    },
    {
        countryCode: 'US',
        coordinates: '+421953-0830245',
        timeZone   : 'America/Detroit',
        comments   : 'Eastern - MI (most areas)',
    },
    {
        countryCode: 'DM',
        coordinates: '+1518-06124',
        timeZone   : 'America/Dominica',
    },
    {
        countryCode: 'CA',
        coordinates: '+5333-11328',
        timeZone   : 'America/Edmonton',
        comments   : 'Mountain - AB; BC (E); SK (W)',
    },
    {
        countryCode: 'BR',
        coordinates: '-0640-06952',
        timeZone   : 'America/Eirunepe',
        comments   : 'Amazonas (west)',
    },
    {
        countryCode: 'SV',
        coordinates: '+1342-08912',
        timeZone   : 'America/El_Salvador',
    },
    {
        countryCode: 'CA',
        coordinates: '+5848-12242',
        timeZone   : 'America/Fort_Nelson',
        comments   : 'MST - BC (Ft Nelson)',
    },
    {
        countryCode: 'BR',
        coordinates: '-0343-03830',
        timeZone   : 'America/Fortaleza',
        comments   : 'Brazil (northeast: MA, PI, CE, RN, PB)',
    },
    {
        countryCode: 'CA',
        coordinates: '+4612-05957',
        timeZone   : 'America/Glace_Bay',
        comments   : 'Atlantic - NS (Cape Breton)',
    },
    {
        countryCode: 'CA',
        coordinates: '+5320-06025',
        timeZone   : 'America/Goose_Bay',
        comments   : 'Atlantic - Labrador (most areas)',
    },
    {
        countryCode: 'TC',
        coordinates: '+2128-07108',
        timeZone   : 'America/Grand_Turk',
    },
    {
        countryCode: 'GD',
        coordinates: '+1203-06145',
        timeZone   : 'America/Grenada',
    },
    {
        countryCode: 'GP',
        coordinates: '+1614-06132',
        timeZone   : 'America/Guadeloupe',
    },
    {
        countryCode: 'GT',
        coordinates: '+1438-09031',
        timeZone   : 'America/Guatemala',
    },
    {
        countryCode: 'EC',
        coordinates: '-0210-07950',
        timeZone   : 'America/Guayaquil',
        comments   : 'Ecuador (mainland)',
    },
    {
        countryCode: 'GY',
        coordinates: '+0648-05810',
        timeZone   : 'America/Guyana',
    },
    {
        countryCode: 'CA',
        coordinates: '+4439-06336',
        timeZone   : 'America/Halifax',
        comments   : 'Atlantic - NS (most areas); PE',
    },
    {
        countryCode: 'CU',
        coordinates: '+2308-08222',
        timeZone   : 'America/Havana',
    },
    {
        countryCode: 'MX',
        coordinates: '+2904-11058',
        timeZone   : 'America/Hermosillo',
        comments   : 'Mountain Standard Time - Sonora',
    },
    {
        countryCode: 'US',
        coordinates: '+394606-0860929',
        timeZone   : 'America/Indiana/Indianapolis',
        comments   : 'Eastern - IN (most areas)',
    },
    {
        countryCode: 'US',
        coordinates: '+411745-0863730',
        timeZone   : 'America/Indiana/Knox',
        comments   : 'Central - IN (Starke)',
    },
    {
        countryCode: 'US',
        coordinates: '+382232-0862041',
        timeZone   : 'America/Indiana/Marengo',
        comments   : 'Eastern - IN (Crawford)',
    },
    {
        countryCode: 'US',
        coordinates: '+382931-0871643',
        timeZone   : 'America/Indiana/Petersburg',
        comments   : 'Eastern - IN (Pike)',
    },
    {
        countryCode: 'US',
        coordinates: '+375711-0864541',
        timeZone   : 'America/Indiana/Tell_City',
        comments   : 'Central - IN (Perry)',
    },
    {
        countryCode: 'US',
        coordinates: '+384452-0850402',
        timeZone   : 'America/Indiana/Vevay',
        comments   : 'Eastern - IN (Switzerland)',
    },
    {
        countryCode: 'US',
        coordinates: '+384038-0873143',
        timeZone   : 'America/Indiana/Vincennes',
        comments   : 'Eastern - IN (Da, Du, K, Mn)',
    },
    {
        countryCode: 'US',
        coordinates: '+410305-0863611',
        timeZone   : 'America/Indiana/Winamac',
        comments   : 'Eastern - IN (Pulaski)',
    },
    {
        countryCode: 'CA',
        coordinates: '+682059-1334300',
        timeZone   : 'America/Inuvik',
        comments   : 'Mountain - NT (west)',
    },
    {
        countryCode: 'CA',
        coordinates: '+6344-06828',
        timeZone   : 'America/Iqaluit',
        comments   : 'Eastern - NU (most east areas)',
    },
    {
        countryCode: 'JM',
        coordinates: '+175805-0764736',
        timeZone   : 'America/Jamaica',
    },
    {
        countryCode: 'US',
        coordinates: '+581807-1342511',
        timeZone   : 'America/Juneau',
        comments   : 'Alaska - Juneau area',
    },
    {
        countryCode: 'US',
        coordinates: '+381515-0854534',
        timeZone   : 'America/Kentucky/Louisville',
        comments   : 'Eastern - KY (Louisville area)',
    },
    {
        countryCode: 'US',
        coordinates: '+364947-0845057',
        timeZone   : 'America/Kentucky/Monticello',
        comments   : 'Eastern - KY (Wayne)',
    },
    {
        countryCode: 'BQ',
        coordinates: '+120903-0681636',
        timeZone   : 'America/Kralendijk',
    },
    {
        countryCode: 'BO',
        coordinates: '-1630-06809',
        timeZone   : 'America/La_Paz',
    },
    {
        countryCode: 'PE',
        coordinates: '-1203-07703',
        timeZone   : 'America/Lima',
    },
    {
        countryCode: 'US',
        coordinates: '+340308-1181434',
        timeZone   : 'America/Los_Angeles',
        comments   : 'Pacific',
    },
    {
        countryCode: 'SX',
        coordinates: '+180305-0630250',
        timeZone   : 'America/Lower_Princes',
    },
    {
        countryCode: 'BR',
        coordinates: '-0940-03543',
        timeZone   : 'America/Maceio',
        comments   : 'Alagoas, Sergipe',
    },
    {
        countryCode: 'NI',
        coordinates: '+1209-08617',
        timeZone   : 'America/Managua',
    },
    {
        countryCode: 'BR',
        coordinates: '-0308-06001',
        timeZone   : 'America/Manaus',
        comments   : 'Amazonas (east)',
    },
    {
        countryCode: 'MF',
        coordinates: '+1804-06305',
        timeZone   : 'America/Marigot',
    },
    {
        countryCode: 'MQ',
        coordinates: '+1436-06105',
        timeZone   : 'America/Martinique',
    },
    {
        countryCode: 'MX',
        coordinates: '+2550-09730',
        timeZone   : 'America/Matamoros',
        comments   : 'Central Time US - Coahuila, Nuevo Leon, Tamaulipas (US border)',
    },
    {
        countryCode: 'MX',
        coordinates: '+2313-10625',
        timeZone   : 'America/Mazatlan',
        comments   : 'Mountain Time - Baja California Sur, Nayarit, Sinaloa',
    },
    {
        countryCode: 'US',
        coordinates: '+450628-0873651',
        timeZone   : 'America/Menominee',
        comments   : 'Central - MI (Wisconsin border)',
    },
    {
        countryCode: 'MX',
        coordinates: '+2058-08937',
        timeZone   : 'America/Merida',
        comments   : 'Central Time - Campeche, Yucatan',
    },
    {
        countryCode: 'US',
        coordinates: '+550737-1313435',
        timeZone   : 'America/Metlakatla',
        comments   : 'Alaska - Annette Island',
    },
    {
        countryCode: 'MX',
        coordinates: '+1924-09909',
        timeZone   : 'America/Mexico_City',
        comments   : 'Central Time',
    },
    {
        countryCode: 'PM',
        coordinates: '+4703-05620',
        timeZone   : 'America/Miquelon',
    },
    {
        countryCode: 'CA',
        coordinates: '+4606-06447',
        timeZone   : 'America/Moncton',
        comments   : 'Atlantic - New Brunswick',
    },
    {
        countryCode: 'MX',
        coordinates: '+2540-10019',
        timeZone   : 'America/Monterrey',
        comments   : 'Central Time - Durango; Coahuila, Nuevo Leon, Tamaulipas (most areas)',
    },
    {
        countryCode: 'UY',
        coordinates: '-345433-0561245',
        timeZone   : 'America/Montevideo',
    },
    {
        countryCode: 'MS',
        coordinates: '+1643-06213',
        timeZone   : 'America/Montserrat',
    },
    {
        countryCode: 'BS',
        coordinates: '+2505-07721',
        timeZone   : 'America/Nassau',
    },
    {
        countryCode: 'US',
        coordinates: '+404251-0740023',
        timeZone   : 'America/New_York',
        comments   : 'Eastern (most areas)',
    },
    {
        countryCode: 'CA',
        coordinates: '+4901-08816',
        timeZone   : 'America/Nipigon',
        comments   : 'Eastern - ON, QC (no DST 1967-73)',
    },
    {
        countryCode: 'US',
        coordinates: '+643004-1652423',
        timeZone   : 'America/Nome',
        comments   : 'Alaska (west)',
    },
    {
        countryCode: 'BR',
        coordinates: '-0351-03225',
        timeZone   : 'America/Noronha',
        comments   : 'Atlantic islands',
    },
    {
        countryCode: 'US',
        coordinates: '+471551-1014640',
        timeZone   : 'America/North_Dakota/Beulah',
        comments   : 'Central - ND (Mercer)',
    },
    {
        countryCode: 'US',
        coordinates: '+470659-1011757',
        timeZone   : 'America/North_Dakota/Center',
        comments   : 'Central - ND (Oliver)',
    },
    {
        countryCode: 'US',
        coordinates: '+465042-1012439',
        timeZone   : 'America/North_Dakota/New_Salem',
        comments   : 'Central - ND (Morton rural)',
    },
    {
        countryCode: 'GL',
        coordinates: '+6411-05144',
        timeZone   : 'America/Nuuk',
        comments   : 'Greenland (most areas)',
    },
    {
        countryCode: 'MX',
        coordinates: '+2934-10425',
        timeZone   : 'America/Ojinaga',
        comments   : 'Mountain Time US - Chihuahua (US border)',
    },
    {
        countryCode: 'PA',
        coordinates: '+0858-07932',
        timeZone   : 'America/Panama',
    },
    {
        countryCode: 'CA',
        coordinates: '+6608-06544',
        timeZone   : 'America/Pangnirtung',
        comments   : 'Eastern - NU (Pangnirtung)',
    },
    {
        countryCode: 'SR',
        coordinates: '+0550-05510',
        timeZone   : 'America/Paramaribo',
    },
    {
        countryCode: 'US',
        coordinates: '+332654-1120424',
        timeZone   : 'America/Phoenix',
        comments   : 'MST - Arizona (except Navajo)',
    },
    {
        countryCode: 'HT',
        coordinates: '+1832-07220',
        timeZone   : 'America/Port-au-Prince',
    },
    {
        countryCode: 'TT',
        coordinates: '+1039-06131',
        timeZone   : 'America/Port_of_Spain',
    },
    {
        countryCode: 'BR',
        coordinates: '-0846-06354',
        timeZone   : 'America/Porto_Velho',
        comments   : 'Rondonia',
    },
    {
        countryCode: 'PR',
        coordinates: '+182806-0660622',
        timeZone   : 'America/Puerto_Rico',
    },
    {
        countryCode: 'CL',
        coordinates: '-5309-07055',
        timeZone   : 'America/Punta_Arenas',
        comments   : 'Region of Magallanes',
    },
    {
        countryCode: 'CA',
        coordinates: '+4843-09434',
        timeZone   : 'America/Rainy_River',
        comments   : 'Central - ON (Rainy R, Ft Frances)',
    },
    {
        countryCode: 'CA',
        coordinates: '+624900-0920459',
        timeZone   : 'America/Rankin_Inlet',
        comments   : 'Central - NU (central)',
    },
    {
        countryCode: 'BR',
        coordinates: '-0803-03454',
        timeZone   : 'America/Recife',
        comments   : 'Pernambuco',
    },
    {
        countryCode: 'CA',
        coordinates: '+5024-10439',
        timeZone   : 'America/Regina',
        comments   : 'CST - SK (most areas)',
    },
    {
        countryCode: 'CA',
        coordinates: '+744144-0944945',
        timeZone   : 'America/Resolute',
        comments   : 'Central - NU (Resolute)',
    },
    {
        countryCode: 'BR',
        coordinates: '-0958-06748',
        timeZone   : 'America/Rio_Branco',
        comments   : 'Acre',
    },
    {
        countryCode: 'BR',
        coordinates: '-0226-05452',
        timeZone   : 'America/Santarem',
        comments   : 'Para (west)',
    },
    {
        countryCode: 'CL',
        coordinates: '-3327-07040',
        timeZone   : 'America/Santiago',
        comments   : 'Chile (most areas)',
    },
    {
        countryCode: 'DO',
        coordinates: '+1828-06954',
        timeZone   : 'America/Santo_Domingo',
    },
    {
        countryCode: 'BR',
        coordinates: '-2332-04637',
        timeZone   : 'America/Sao_Paulo',
        comments   : 'Brazil (southeast: GO, DF, MG, ES, RJ, SP, PR, SC, RS)',
    },
    {
        countryCode: 'GL',
        coordinates: '+7029-02158',
        timeZone   : 'America/Scoresbysund',
        comments   : 'Scoresbysund/Ittoqqortoormiit',
    },
    {
        countryCode: 'US',
        coordinates: '+571035-1351807',
        timeZone   : 'America/Sitka',
        comments   : 'Alaska - Sitka area',
    },
    {
        countryCode: 'BL',
        coordinates: '+1753-06251',
        timeZone   : 'America/St_Barthelemy',
    },
    {
        countryCode: 'CA',
        coordinates: '+4734-05243',
        timeZone   : 'America/St_Johns',
        comments   : 'Newfoundland; Labrador (southeast)',
    },
    {
        countryCode: 'KN',
        coordinates: '+1718-06243',
        timeZone   : 'America/St_Kitts',
    },
    {
        countryCode: 'LC',
        coordinates: '+1401-06100',
        timeZone   : 'America/St_Lucia',
    },
    {
        countryCode: 'VI',
        coordinates: '+1821-06456',
        timeZone   : 'America/St_Thomas',
    },
    {
        countryCode: 'VC',
        coordinates: '+1309-06114',
        timeZone   : 'America/St_Vincent',
    },
    {
        countryCode: 'CA',
        coordinates: '+5017-10750',
        timeZone   : 'America/Swift_Current',
        comments   : 'CST - SK (midwest)',
    },
    {
        countryCode: 'HN',
        coordinates: '+1406-08713',
        timeZone   : 'America/Tegucigalpa',
    },
    {
        countryCode: 'GL',
        coordinates: '+7634-06847',
        timeZone   : 'America/Thule',
        comments   : 'Thule/Pituffik',
    },
    {
        countryCode: 'CA',
        coordinates: '+4823-08915',
        timeZone   : 'America/Thunder_Bay',
        comments   : 'Eastern - ON (Thunder Bay)',
    },
    {
        countryCode: 'MX',
        coordinates: '+3232-11701',
        timeZone   : 'America/Tijuana',
        comments   : 'Pacific Time US - Baja California',
    },
    {
        countryCode: 'CA',
        coordinates: '+4339-07923',
        timeZone   : 'America/Toronto',
        comments   : 'Eastern - ON, QC (most areas)',
    },
    {
        countryCode: 'VG',
        coordinates: '+1827-06437',
        timeZone   : 'America/Tortola',
    },
    {
        countryCode: 'CA',
        coordinates: '+4916-12307',
        timeZone   : 'America/Vancouver',
        comments   : 'Pacific - BC (most areas)',
    },
    {
        countryCode: 'CA',
        coordinates: '+6043-13503',
        timeZone   : 'America/Whitehorse',
        comments   : 'MST - Yukon (east)',
    },
    {
        countryCode: 'CA',
        coordinates: '+4953-09709',
        timeZone   : 'America/Winnipeg',
        comments   : 'Central - ON (west); Manitoba',
    },
    {
        countryCode: 'US',
        coordinates: '+593249-1394338',
        timeZone   : 'America/Yakutat',
        comments   : 'Alaska - Yakutat',
    },
    {
        countryCode: 'CA',
        coordinates: '+6227-11421',
        timeZone   : 'America/Yellowknife',
        comments   : 'Mountain - NT (central)',
    },
    {
        countryCode: 'AQ',
        coordinates: '-6617+11031',
        timeZone   : 'Antarctica/Casey',
        comments   : 'Casey',
    },
    {
        countryCode: 'AQ',
        coordinates: '-6835+07758',
        timeZone   : 'Antarctica/Davis',
        comments   : 'Davis',
    },
    {
        countryCode: 'AQ',
        coordinates: '-6640+14001',
        timeZone   : 'Antarctica/DumontDUrville',
        comments   : 'Dumont-d\'Urville',
    },
    {
        countryCode: 'AU',
        coordinates: '-5430+15857',
        timeZone   : 'Antarctica/Macquarie',
        comments   : 'Macquarie Island',
    },
    {
        countryCode: 'AQ',
        coordinates: '-6736+06253',
        timeZone   : 'Antarctica/Mawson',
        comments   : 'Mawson',
    },
    {
        countryCode: 'AQ',
        coordinates: '-7750+16636',
        timeZone   : 'Antarctica/McMurdo',
        comments   : 'New Zealand time - McMurdo, South Pole',
    },
    {
        countryCode: 'AQ',
        coordinates: '-6448-06406',
        timeZone   : 'Antarctica/Palmer',
        comments   : 'Palmer',
    },
    {
        countryCode: 'AQ',
        coordinates: '-6734-06808',
        timeZone   : 'Antarctica/Rothera',
        comments   : 'Rothera',
    },
    {
        countryCode: 'AQ',
        coordinates: '-690022+0393524',
        timeZone   : 'Antarctica/Syowa',
        comments   : 'Syowa',
    },
    {
        countryCode: 'AQ',
        coordinates: '-720041+0023206',
        timeZone   : 'Antarctica/Troll',
        comments   : 'Troll',
    },
    {
        countryCode: 'AQ',
        coordinates: '-7824+10654',
        timeZone   : 'Antarctica/Vostok',
        comments   : 'Vostok',
    },
    {
        countryCode: 'SJ',
        coordinates: '+7800+01600',
        timeZone   : 'Arctic/Longyearbyen',
    },
    {
        countryCode: 'YE',
        coordinates: '+1245+04512',
        timeZone   : 'Asia/Aden',
    },
    {
        countryCode: 'KZ',
        coordinates: '+4315+07657',
        timeZone   : 'Asia/Almaty',
        comments   : 'Kazakhstan (most areas)',
    },
    {
        countryCode: 'JO',
        coordinates: '+3157+03556',
        timeZone   : 'Asia/Amman',
    },
    {
        countryCode: 'RU',
        coordinates: '+6445+17729',
        timeZone   : 'Asia/Anadyr',
        comments   : 'MSK+09 - Bering Sea',
    },
    {
        countryCode: 'KZ',
        coordinates: '+4431+05016',
        timeZone   : 'Asia/Aqtau',
        comments   : 'Mangghystau/Mankistau',
    },
    {
        countryCode: 'KZ',
        coordinates: '+5017+05710',
        timeZone   : 'Asia/Aqtobe',
        comments   : 'Aqtobe/Aktobe',
    },
    {
        countryCode: 'TM',
        coordinates: '+3757+05823',
        timeZone   : 'Asia/Ashgabat',
    },
    {
        countryCode: 'KZ',
        coordinates: '+4707+05156',
        timeZone   : 'Asia/Atyrau',
        comments   : 'Atyrau/Atirau/Gur\'yev',
    },
    {
        countryCode: 'IQ',
        coordinates: '+3321+04425',
        timeZone   : 'Asia/Baghdad',
    },
    {
        countryCode: 'BH',
        coordinates: '+2623+05035',
        timeZone   : 'Asia/Bahrain',
    },
    {
        countryCode: 'AZ',
        coordinates: '+4023+04951',
        timeZone   : 'Asia/Baku',
    },
    {
        countryCode: 'TH',
        coordinates: '+1345+10031',
        timeZone   : 'Asia/Bangkok',
    },
    {
        countryCode: 'RU',
        coordinates: '+5322+08345',
        timeZone   : 'Asia/Barnaul',
        comments   : 'MSK+04 - Altai',
    },
    {
        countryCode: 'LB',
        coordinates: '+3353+03530',
        timeZone   : 'Asia/Beirut',
    },
    {
        countryCode: 'KG',
        coordinates: '+4254+07436',
        timeZone   : 'Asia/Bishkek',
    },
    {
        countryCode: 'BN',
        coordinates: '+0456+11455',
        timeZone   : 'Asia/Brunei',
    },
    {
        countryCode: 'RU',
        coordinates: '+5203+11328',
        timeZone   : 'Asia/Chita',
        comments   : 'MSK+06 - Zabaykalsky',
    },
    {
        countryCode: 'MN',
        coordinates: '+4804+11430',
        timeZone   : 'Asia/Choibalsan',
        comments   : 'Dornod, Sukhbaatar',
    },
    {
        countryCode: 'LK',
        coordinates: '+0656+07951',
        timeZone   : 'Asia/Colombo',
    },
    {
        countryCode: 'SY',
        coordinates: '+3330+03618',
        timeZone   : 'Asia/Damascus',
    },
    {
        countryCode: 'BD',
        coordinates: '+2343+09025',
        timeZone   : 'Asia/Dhaka',
    },
    {
        countryCode: 'TL',
        coordinates: '-0833+12535',
        timeZone   : 'Asia/Dili',
    },
    {
        countryCode: 'AE',
        coordinates: '+2518+05518',
        timeZone   : 'Asia/Dubai',
    },
    {
        countryCode: 'TJ',
        coordinates: '+3835+06848',
        timeZone   : 'Asia/Dushanbe',
    },
    {
        countryCode: 'CY',
        coordinates: '+3507+03357',
        timeZone   : 'Asia/Famagusta',
        comments   : 'Northern Cyprus',
    },
    {
        countryCode: 'PS',
        coordinates: '+3130+03428',
        timeZone   : 'Asia/Gaza',
        comments   : 'Gaza Strip',
    },
    {
        countryCode: 'PS',
        coordinates: '+313200+0350542',
        timeZone   : 'Asia/Hebron',
        comments   : 'West Bank',
    },
    {
        countryCode: 'VN',
        coordinates: '+1045+10640',
        timeZone   : 'Asia/Ho_Chi_Minh',
    },
    {
        countryCode: 'HK',
        coordinates: '+2217+11409',
        timeZone   : 'Asia/Hong_Kong',
    },
    {
        countryCode: 'MN',
        coordinates: '+4801+09139',
        timeZone   : 'Asia/Hovd',
        comments   : 'Bayan-Olgiy, Govi-Altai, Hovd, Uvs, Zavkhan',
    },
    {
        countryCode: 'RU',
        coordinates: '+5216+10420',
        timeZone   : 'Asia/Irkutsk',
        comments   : 'MSK+05 - Irkutsk, Buryatia',
    },
    {
        countryCode: 'ID',
        coordinates: '-0610+10648',
        timeZone   : 'Asia/Jakarta',
        comments   : 'Java, Sumatra',
    },
    {
        countryCode: 'ID',
        coordinates: '-0232+14042',
        timeZone   : 'Asia/Jayapura',
        comments   : 'New Guinea (West Papua / Irian Jaya); Malukus/Moluccas',
    },
    {
        countryCode: 'IL',
        coordinates: '+314650+0351326',
        timeZone   : 'Asia/Jerusalem',
    },
    {
        countryCode: 'AF',
        coordinates: '+3431+06912',
        timeZone   : 'Asia/Kabul',
    },
    {
        countryCode: 'RU',
        coordinates: '+5301+15839',
        timeZone   : 'Asia/Kamchatka',
        comments   : 'MSK+09 - Kamchatka',
    },
    {
        countryCode: 'PK',
        coordinates: '+2452+06703',
        timeZone   : 'Asia/Karachi',
    },
    {
        countryCode: 'NP',
        coordinates: '+2743+08519',
        timeZone   : 'Asia/Kathmandu',
    },
    {
        countryCode: 'RU',
        coordinates: '+623923+1353314',
        timeZone   : 'Asia/Khandyga',
        comments   : 'MSK+06 - Tomponsky, Ust-Maysky',
    },
    {
        countryCode: 'IN',
        coordinates: '+2232+08822',
        timeZone   : 'Asia/Kolkata',
    },
    {
        countryCode: 'RU',
        coordinates: '+5601+09250',
        timeZone   : 'Asia/Krasnoyarsk',
        comments   : 'MSK+04 - Krasnoyarsk area',
    },
    {
        countryCode: 'MY',
        coordinates: '+0310+10142',
        timeZone   : 'Asia/Kuala_Lumpur',
        comments   : 'Malaysia (peninsula)',
    },
    {
        countryCode: 'MY',
        coordinates: '+0133+11020',
        timeZone   : 'Asia/Kuching',
        comments   : 'Sabah, Sarawak',
    },
    {
        countryCode: 'KW',
        coordinates: '+2920+04759',
        timeZone   : 'Asia/Kuwait',
    },
    {
        countryCode: 'MO',
        coordinates: '+221150+1133230',
        timeZone   : 'Asia/Macau',
    },
    {
        countryCode: 'RU',
        coordinates: '+5934+15048',
        timeZone   : 'Asia/Magadan',
        comments   : 'MSK+08 - Magadan',
    },
    {
        countryCode: 'ID',
        coordinates: '-0507+11924',
        timeZone   : 'Asia/Makassar',
        comments   : 'Borneo (east, south); Sulawesi/Celebes, Bali, Nusa Tengarra; Timor (west)',
    },
    {
        countryCode: 'PH',
        coordinates: '+1435+12100',
        timeZone   : 'Asia/Manila',
    },
    {
        countryCode: 'OM',
        coordinates: '+2336+05835',
        timeZone   : 'Asia/Muscat',
    },
    {
        countryCode: 'CY',
        coordinates: '+3510+03322',
        timeZone   : 'Asia/Nicosia',
        comments   : 'Cyprus (most areas)',
    },
    {
        countryCode: 'RU',
        coordinates: '+5345+08707',
        timeZone   : 'Asia/Novokuznetsk',
        comments   : 'MSK+04 - Kemerovo',
    },
    {
        countryCode: 'RU',
        coordinates: '+5502+08255',
        timeZone   : 'Asia/Novosibirsk',
        comments   : 'MSK+04 - Novosibirsk',
    },
    {
        countryCode: 'RU',
        coordinates: '+5500+07324',
        timeZone   : 'Asia/Omsk',
        comments   : 'MSK+03 - Omsk',
    },
    {
        countryCode: 'KZ',
        coordinates: '+5113+05121',
        timeZone   : 'Asia/Oral',
        comments   : 'West Kazakhstan',
    },
    {
        countryCode: 'KH',
        coordinates: '+1133+10455',
        timeZone   : 'Asia/Phnom_Penh',
    },
    {
        countryCode: 'ID',
        coordinates: '-0002+10920',
        timeZone   : 'Asia/Pontianak',
        comments   : 'Borneo (west, central)',
    },
    {
        countryCode: 'KP',
        coordinates: '+3901+12545',
        timeZone   : 'Asia/Pyongyang',
    },
    {
        countryCode: 'QA',
        coordinates: '+2517+05132',
        timeZone   : 'Asia/Qatar',
    },
    {
        countryCode: 'KZ',
        coordinates: '+5312+06337',
        timeZone   : 'Asia/Qostanay',
        comments   : 'Qostanay/Kostanay/Kustanay',
    },
    {
        countryCode: 'KZ',
        coordinates: '+4448+06528',
        timeZone   : 'Asia/Qyzylorda',
        comments   : 'Qyzylorda/Kyzylorda/Kzyl-Orda',
    },
    {
        countryCode: 'SA',
        coordinates: '+2438+04643',
        timeZone   : 'Asia/Riyadh',
    },
    {
        countryCode: 'RU',
        coordinates: '+4658+14242',
        timeZone   : 'Asia/Sakhalin',
        comments   : 'MSK+08 - Sakhalin Island',
    },
    {
        countryCode: 'UZ',
        coordinates: '+3940+06648',
        timeZone   : 'Asia/Samarkand',
        comments   : 'Uzbekistan (west)',
    },
    {
        countryCode: 'KR',
        coordinates: '+3733+12658',
        timeZone   : 'Asia/Seoul',
    },
    {
        countryCode: 'CN',
        coordinates: '+3114+12128',
        timeZone   : 'Asia/Shanghai',
        comments   : 'Beijing Time',
    },
    {
        countryCode: 'SG',
        coordinates: '+0117+10351',
        timeZone   : 'Asia/Singapore',
    },
    {
        countryCode: 'RU',
        coordinates: '+6728+15343',
        timeZone   : 'Asia/Srednekolymsk',
        comments   : 'MSK+08 - Sakha (E); North Kuril Is',
    },
    {
        countryCode: 'TW',
        coordinates: '+2503+12130',
        timeZone   : 'Asia/Taipei',
    },
    {
        countryCode: 'UZ',
        coordinates: '+4120+06918',
        timeZone   : 'Asia/Tashkent',
        comments   : 'Uzbekistan (east)',
    },
    {
        countryCode: 'GE',
        coordinates: '+4143+04449',
        timeZone   : 'Asia/Tbilisi',
    },
    {
        countryCode: 'IR',
        coordinates: '+3540+05126',
        timeZone   : 'Asia/Tehran',
    },
    {
        countryCode: 'BT',
        coordinates: '+2728+08939',
        timeZone   : 'Asia/Thimphu',
    },
    {
        countryCode: 'JP',
        coordinates: '+353916+1394441',
        timeZone   : 'Asia/Tokyo',
    },
    {
        countryCode: 'RU',
        coordinates: '+5630+08458',
        timeZone   : 'Asia/Tomsk',
        comments   : 'MSK+04 - Tomsk',
    },
    {
        countryCode: 'MN',
        coordinates: '+4755+10653',
        timeZone   : 'Asia/Ulaanbaatar',
        comments   : 'Mongolia (most areas)',
    },
    {
        countryCode: 'CN',
        coordinates: '+4348+08735',
        timeZone   : 'Asia/Urumqi',
        comments   : 'Xinjiang Time',
    },
    {
        countryCode: 'RU',
        coordinates: '+643337+1431336',
        timeZone   : 'Asia/Ust-Nera',
        comments   : 'MSK+07 - Oymyakonsky',
    },
    {
        countryCode: 'LA',
        coordinates: '+1758+10236',
        timeZone   : 'Asia/Vientiane',
    },
    {
        countryCode: 'RU',
        coordinates: '+4310+13156',
        timeZone   : 'Asia/Vladivostok',
        comments   : 'MSK+07 - Amur River',
    },
    {
        countryCode: 'RU',
        coordinates: '+6200+12940',
        timeZone   : 'Asia/Yakutsk',
        comments   : 'MSK+06 - Lena River',
    },
    {
        countryCode: 'MM',
        coordinates: '+1647+09610',
        timeZone   : 'Asia/Yangon',
    },
    {
        countryCode: 'RU',
        coordinates: '+5651+06036',
        timeZone   : 'Asia/Yekaterinburg',
        comments   : 'MSK+02 - Urals',
    },
    {
        countryCode: 'AM',
        coordinates: '+4011+04430',
        timeZone   : 'Asia/Yerevan',
    },
    {
        countryCode: 'PT',
        coordinates: '+3744-02540',
        timeZone   : 'Atlantic/Azores',
        comments   : 'Azores',
    },
    {
        countryCode: 'BM',
        coordinates: '+3217-06446',
        timeZone   : 'Atlantic/Bermuda',
    },
    {
        countryCode: 'ES',
        coordinates: '+2806-01524',
        timeZone   : 'Atlantic/Canary',
        comments   : 'Canary Islands',
    },
    {
        countryCode: 'CV',
        coordinates: '+1455-02331',
        timeZone   : 'Atlantic/Cape_Verde',
    },
    {
        countryCode: 'FO',
        coordinates: '+6201-00646',
        timeZone   : 'Atlantic/Faroe',
    },
    {
        countryCode: 'PT',
        coordinates: '+3238-01654',
        timeZone   : 'Atlantic/Madeira',
        comments   : 'Madeira Islands',
    },
    {
        countryCode: 'IS',
        coordinates: '+6409-02151',
        timeZone   : 'Atlantic/Reykjavik',
    },
    {
        countryCode: 'GS',
        coordinates: '-5416-03632',
        timeZone   : 'Atlantic/South_Georgia',
    },
    {
        countryCode: 'SH',
        coordinates: '-1555-00542',
        timeZone   : 'Atlantic/St_Helena',
    },
    {
        countryCode: 'FK',
        coordinates: '-5142-05751',
        timeZone   : 'Atlantic/Stanley',
    },
    {
        countryCode: 'AU',
        coordinates: '-3455+13835',
        timeZone   : 'Australia/Adelaide',
        comments   : 'South Australia',
    },
    {
        countryCode: 'AU',
        coordinates: '-2728+15302',
        timeZone   : 'Australia/Brisbane',
        comments   : 'Queensland (most areas)',
    },
    {
        countryCode: 'AU',
        coordinates: '-3157+14127',
        timeZone   : 'Australia/Broken_Hill',
        comments   : 'New South Wales (Yancowinna)',
    },
    {
        countryCode: 'AU',
        coordinates: '-1228+13050',
        timeZone   : 'Australia/Darwin',
        comments   : 'Northern Territory',
    },
    {
        countryCode: 'AU',
        coordinates: '-3143+12852',
        timeZone   : 'Australia/Eucla',
        comments   : 'Western Australia (Eucla)',
    },
    {
        countryCode: 'AU',
        coordinates: '-4253+14719',
        timeZone   : 'Australia/Hobart',
        comments   : 'Tasmania',
    },
    {
        countryCode: 'AU',
        coordinates: '-2016+14900',
        timeZone   : 'Australia/Lindeman',
        comments   : 'Queensland (Whitsunday Islands)',
    },
    {
        countryCode: 'AU',
        coordinates: '-3133+15905',
        timeZone   : 'Australia/Lord_Howe',
        comments   : 'Lord Howe Island',
    },
    {
        countryCode: 'AU',
        coordinates: '-3749+14458',
        timeZone   : 'Australia/Melbourne',
        comments   : 'Victoria',
    },
    {
        countryCode: 'AU',
        coordinates: '-3157+11551',
        timeZone   : 'Australia/Perth',
        comments   : 'Western Australia (most areas)',
    },
    {
        countryCode: 'AU',
        coordinates: '-3352+15113',
        timeZone   : 'Australia/Sydney',
        comments   : 'New South Wales (most areas)',
    },
    {
        countryCode: 'NL',
        coordinates: '+5222+00454',
        timeZone   : 'Europe/Amsterdam',
    },
    {
        countryCode: 'AD',
        coordinates: '+4230+00131',
        timeZone   : 'Europe/Andorra',
    },
    {
        countryCode: 'RU',
        coordinates: '+4621+04803',
        timeZone   : 'Europe/Astrakhan',
        comments   : 'MSK+01 - Astrakhan',
    },
    {
        countryCode: 'GR',
        coordinates: '+3758+02343',
        timeZone   : 'Europe/Athens',
    },
    {
        countryCode: 'RS',
        coordinates: '+4450+02030',
        timeZone   : 'Europe/Belgrade',
    },
    {
        countryCode: 'DE',
        coordinates: '+5230+01322',
        timeZone   : 'Europe/Berlin',
        comments   : 'Germany (most areas)',
    },
    {
        countryCode: 'SK',
        coordinates: '+4809+01707',
        timeZone   : 'Europe/Bratislava',
    },
    {
        countryCode: 'BE',
        coordinates: '+5050+00420',
        timeZone   : 'Europe/Brussels',
    },
    {
        countryCode: 'RO',
        coordinates: '+4426+02606',
        timeZone   : 'Europe/Bucharest',
    },
    {
        countryCode: 'HU',
        coordinates: '+4730+01905',
        timeZone   : 'Europe/Budapest',
    },
    {
        countryCode: 'DE',
        coordinates: '+4742+00841',
        timeZone   : 'Europe/Busingen',
        comments   : 'Busingen',
    },
    {
        countryCode: 'MD',
        coordinates: '+4700+02850',
        timeZone   : 'Europe/Chisinau',
    },
    {
        countryCode: 'DK',
        coordinates: '+5540+01235',
        timeZone   : 'Europe/Copenhagen',
    },
    {
        countryCode: 'IE',
        coordinates: '+5320-00615',
        timeZone   : 'Europe/Dublin',
    },
    {
        countryCode: 'GI',
        coordinates: '+3608-00521',
        timeZone   : 'Europe/Gibraltar',
    },
    {
        countryCode: 'GG',
        coordinates: '+492717-0023210',
        timeZone   : 'Europe/Guernsey',
    },
    {
        countryCode: 'FI',
        coordinates: '+6010+02458',
        timeZone   : 'Europe/Helsinki',
    },
    {
        countryCode: 'IM',
        coordinates: '+5409-00428',
        timeZone   : 'Europe/Isle_of_Man',
    },
    {
        countryCode: 'TR',
        coordinates: '+4101+02858',
        timeZone   : 'Europe/Istanbul',
    },
    {
        countryCode: 'JE',
        coordinates: '+491101-0020624',
        timeZone   : 'Europe/Jersey',
    },
    {
        countryCode: 'RU',
        coordinates: '+5443+02030',
        timeZone   : 'Europe/Kaliningrad',
        comments   : 'MSK-01 - Kaliningrad',
    },
    {
        countryCode: 'UA',
        coordinates: '+5026+03031',
        timeZone   : 'Europe/Kiev',
        comments   : 'Ukraine (most areas)',
    },
    {
        countryCode: 'RU',
        coordinates: '+5836+04939',
        timeZone   : 'Europe/Kirov',
        comments   : 'MSK+00 - Kirov',
    },
    {
        countryCode: 'PT',
        coordinates: '+3843-00908',
        timeZone   : 'Europe/Lisbon',
        comments   : 'Portugal (mainland)',
    },
    {
        countryCode: 'SI',
        coordinates: '+4603+01431',
        timeZone   : 'Europe/Ljubljana',
    },
    {
        countryCode: 'GB',
        coordinates: '+513030-0000731',
        timeZone   : 'Europe/London',
    },
    {
        countryCode: 'LU',
        coordinates: '+4936+00609',
        timeZone   : 'Europe/Luxembourg',
    },
    {
        countryCode: 'ES',
        coordinates: '+4024-00341',
        timeZone   : 'Europe/Madrid',
        comments   : 'Spain (mainland)',
    },
    {
        countryCode: 'MT',
        coordinates: '+3554+01431',
        timeZone   : 'Europe/Malta',
    },
    {
        countryCode: 'AX',
        coordinates: '+6006+01957',
        timeZone   : 'Europe/Mariehamn',
    },
    {
        countryCode: 'BY',
        coordinates: '+5354+02734',
        timeZone   : 'Europe/Minsk',
    },
    {
        countryCode: 'MC',
        coordinates: '+4342+00723',
        timeZone   : 'Europe/Monaco',
    },
    {
        countryCode: 'RU',
        coordinates: '+554521+0373704',
        timeZone   : 'Europe/Moscow',
        comments   : 'MSK+00 - Moscow area',
    },
    {
        countryCode: 'NO',
        coordinates: '+5955+01045',
        timeZone   : 'Europe/Oslo',
    },
    {
        countryCode: 'FR',
        coordinates: '+4852+00220',
        timeZone   : 'Europe/Paris',
    },
    {
        countryCode: 'ME',
        coordinates: '+4226+01916',
        timeZone   : 'Europe/Podgorica',
    },
    {
        countryCode: 'CZ',
        coordinates: '+5005+01426',
        timeZone   : 'Europe/Prague',
    },
    {
        countryCode: 'LV',
        coordinates: '+5657+02406',
        timeZone   : 'Europe/Riga',
    },
    {
        countryCode: 'IT',
        coordinates: '+4154+01229',
        timeZone   : 'Europe/Rome',
    },
    {
        countryCode: 'RU',
        coordinates: '+5312+05009',
        timeZone   : 'Europe/Samara',
        comments   : 'MSK+01 - Samara, Udmurtia',
    },
    {
        countryCode: 'SM',
        coordinates: '+4355+01228',
        timeZone   : 'Europe/San_Marino',
    },
    {
        countryCode: 'BA',
        coordinates: '+4352+01825',
        timeZone   : 'Europe/Sarajevo',
    },
    {
        countryCode: 'RU',
        coordinates: '+5134+04602',
        timeZone   : 'Europe/Saratov',
        comments   : 'MSK+01 - Saratov',
    },
    {
        countryCode: 'UA',
        coordinates: '+4457+03406',
        timeZone   : 'Europe/Simferopol',
        comments   : 'Crimea',
    },
    {
        countryCode: 'MK',
        coordinates: '+4159+02126',
        timeZone   : 'Europe/Skopje',
    },
    {
        countryCode: 'BG',
        coordinates: '+4241+02319',
        timeZone   : 'Europe/Sofia',
    },
    {
        countryCode: 'SE',
        coordinates: '+5920+01803',
        timeZone   : 'Europe/Stockholm',
    },
    {
        countryCode: 'EE',
        coordinates: '+5925+02445',
        timeZone   : 'Europe/Tallinn',
    },
    {
        countryCode: 'AL',
        coordinates: '+4120+01950',
        timeZone   : 'Europe/Tirane',
    },
    {
        countryCode: 'RU',
        coordinates: '+5420+04824',
        timeZone   : 'Europe/Ulyanovsk',
        comments   : 'MSK+01 - Ulyanovsk',
    },
    {
        countryCode: 'UA',
        coordinates: '+4837+02218',
        timeZone   : 'Europe/Uzhgorod',
        comments   : 'Transcarpathia',
    },
    {
        countryCode: 'LI',
        coordinates: '+4709+00931',
        timeZone   : 'Europe/Vaduz',
    },
    {
        countryCode: 'VA',
        coordinates: '+415408+0122711',
        timeZone   : 'Europe/Vatican',
    },
    {
        countryCode: 'AT',
        coordinates: '+4813+01620',
        timeZone   : 'Europe/Vienna',
    },
    {
        countryCode: 'LT',
        coordinates: '+5441+02519',
        timeZone   : 'Europe/Vilnius',
    },
    {
        countryCode: 'RU',
        coordinates: '+4844+04425',
        timeZone   : 'Europe/Volgograd',
        comments   : 'MSK+00 - Volgograd',
    },
    {
        countryCode: 'PL',
        coordinates: '+5215+02100',
        timeZone   : 'Europe/Warsaw',
    },
    {
        countryCode: 'HR',
        coordinates: '+4548+01558',
        timeZone   : 'Europe/Zagreb',
    },
    {
        countryCode: 'UA',
        coordinates: '+4750+03510',
        timeZone   : 'Europe/Zaporozhye',
        comments   : 'Zaporozhye and east Lugansk',
    },
    {
        countryCode: 'CH',
        coordinates: '+4723+00832',
        timeZone   : 'Europe/Zurich',
    },
    {
        countryCode: 'MG',
        coordinates: '-1855+04731',
        timeZone   : 'Indian/Antananarivo',
    },
    {
        countryCode: 'IO',
        coordinates: '-0720+07225',
        timeZone   : 'Indian/Chagos',
    },
    {
        countryCode: 'CX',
        coordinates: '-1025+10543',
        timeZone   : 'Indian/Christmas',
    },
    {
        countryCode: 'CC',
        coordinates: '-1210+09655',
        timeZone   : 'Indian/Cocos',
    },
    {
        countryCode: 'KM',
        coordinates: '-1141+04316',
        timeZone   : 'Indian/Comoro',
    },
    {
        countryCode: 'TF',
        coordinates: '-492110+0701303',
        timeZone   : 'Indian/Kerguelen',
    },
    {
        countryCode: 'SC',
        coordinates: '-0440+05528',
        timeZone   : 'Indian/Mahe',
    },
    {
        countryCode: 'MV',
        coordinates: '+0410+07330',
        timeZone   : 'Indian/Maldives',
    },
    {
        countryCode: 'MU',
        coordinates: '-2010+05730',
        timeZone   : 'Indian/Mauritius',
    },
    {
        countryCode: 'YT',
        coordinates: '-1247+04514',
        timeZone   : 'Indian/Mayotte',
    },
    {
        countryCode: 'RE',
        coordinates: '-2052+05528',
        timeZone   : 'Indian/Reunion',
    },
    {
        countryCode: 'WS',
        coordinates: '-1350-17144',
        timeZone   : 'Pacific/Apia',
    },
    {
        countryCode: 'NZ',
        coordinates: '-3652+17446',
        timeZone   : 'Pacific/Auckland',
        comments   : 'New Zealand (most areas)',
    },
    {
        countryCode: 'PG',
        coordinates: '-0613+15534',
        timeZone   : 'Pacific/Bougainville',
        comments   : 'Bougainville',
    },
    {
        countryCode: 'NZ',
        coordinates: '-4357-17633',
        timeZone   : 'Pacific/Chatham',
        comments   : 'Chatham Islands',
    },
    {
        countryCode: 'FM',
        coordinates: '+0725+15147',
        timeZone   : 'Pacific/Chuuk',
        comments   : 'Chuuk/Truk, Yap',
    },
    {
        countryCode: 'CL',
        coordinates: '-2709-10926',
        timeZone   : 'Pacific/Easter',
        comments   : 'Easter Island',
    },
    {
        countryCode: 'VU',
        coordinates: '-1740+16825',
        timeZone   : 'Pacific/Efate',
    },
    {
        countryCode: 'KI',
        coordinates: '-0308-17105',
        timeZone   : 'Pacific/Enderbury',
        comments   : 'Phoenix Islands',
    },
    {
        countryCode: 'TK',
        coordinates: '-0922-17114',
        timeZone   : 'Pacific/Fakaofo',
    },
    {
        countryCode: 'FJ',
        coordinates: '-1808+17825',
        timeZone   : 'Pacific/Fiji',
    },
    {
        countryCode: 'TV',
        coordinates: '-0831+17913',
        timeZone   : 'Pacific/Funafuti',
    },
    {
        countryCode: 'EC',
        coordinates: '-0054-08936',
        timeZone   : 'Pacific/Galapagos',
        comments   : 'Galapagos Islands',
    },
    {
        countryCode: 'PF',
        coordinates: '-2308-13457',
        timeZone   : 'Pacific/Gambier',
        comments   : 'Gambier Islands',
    },
    {
        countryCode: 'SB',
        coordinates: '-0932+16012',
        timeZone   : 'Pacific/Guadalcanal',
    },
    {
        countryCode: 'GU',
        coordinates: '+1328+14445',
        timeZone   : 'Pacific/Guam',
    },
    {
        countryCode: 'US',
        coordinates: '+211825-1575130',
        timeZone   : 'Pacific/Honolulu',
        comments   : 'Hawaii',
    },
    {
        countryCode: 'KI',
        coordinates: '+0152-15720',
        timeZone   : 'Pacific/Kiritimati',
        comments   : 'Line Islands',
    },
    {
        countryCode: 'FM',
        coordinates: '+0519+16259',
        timeZone   : 'Pacific/Kosrae',
        comments   : 'Kosrae',
    },
    {
        countryCode: 'MH',
        coordinates: '+0905+16720',
        timeZone   : 'Pacific/Kwajalein',
        comments   : 'Kwajalein',
    },
    {
        countryCode: 'MH',
        coordinates: '+0709+17112',
        timeZone   : 'Pacific/Majuro',
        comments   : 'Marshall Islands (most areas)',
    },
    {
        countryCode: 'PF',
        coordinates: '-0900-13930',
        timeZone   : 'Pacific/Marquesas',
        comments   : 'Marquesas Islands',
    },
    {
        countryCode: 'UM',
        coordinates: '+2813-17722',
        timeZone   : 'Pacific/Midway',
        comments   : 'Midway Islands',
    },
    {
        countryCode: 'NR',
        coordinates: '-0031+16655',
        timeZone   : 'Pacific/Nauru',
    },
    {
        countryCode: 'NU',
        coordinates: '-1901-16955',
        timeZone   : 'Pacific/Niue',
    },
    {
        countryCode: 'NF',
        coordinates: '-2903+16758',
        timeZone   : 'Pacific/Norfolk',
    },
    {
        countryCode: 'NC',
        coordinates: '-2216+16627',
        timeZone   : 'Pacific/Noumea',
    },
    {
        countryCode: 'AS',
        coordinates: '-1416-17042',
        timeZone   : 'Pacific/Pago_Pago',
    },
    {
        countryCode: 'PW',
        coordinates: '+0720+13429',
        timeZone   : 'Pacific/Palau',
    },
    {
        countryCode: 'PN',
        coordinates: '-2504-13005',
        timeZone   : 'Pacific/Pitcairn',
    },
    {
        countryCode: 'FM',
        coordinates: '+0658+15813',
        timeZone   : 'Pacific/Pohnpei',
        comments   : 'Pohnpei/Ponape',
    },
    {
        countryCode: 'PG',
        coordinates: '-0930+14710',
        timeZone   : 'Pacific/Port_Moresby',
        comments   : 'Papua New Guinea (most areas)',
    },
    {
        countryCode: 'CK',
        coordinates: '-2114-15946',
        timeZone   : 'Pacific/Rarotonga',
    },
    {
        countryCode: 'MP',
        coordinates: '+1512+14545',
        timeZone   : 'Pacific/Saipan',
    },
    {
        countryCode: 'PF',
        coordinates: '-1732-14934',
        timeZone   : 'Pacific/Tahiti',
        comments   : 'Society Islands',
    },
    {
        countryCode: 'KI',
        coordinates: '+0125+17300',
        timeZone   : 'Pacific/Tarawa',
        comments   : 'Gilbert Islands',
    },
    {
        countryCode: 'TO',
        coordinates: '-2110-17510',
        timeZone   : 'Pacific/Tongatapu',
    },
    {
        countryCode: 'UM',
        coordinates: '+1917+16637',
        timeZone   : 'Pacific/Wake',
        comments   : 'Wake Island',
    },
    {
        countryCode: 'WF',
        coordinates: '-1318-17610',
        timeZone   : 'Pacific/Wallis',
    },
];
